import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.decomposition import PCA
from scipy.spatial.transform import Rotation
import matplotlib.pyplot as plt

import rclpy
from rclpy.node import Node

from sensor_msgs.msg import PointCloud2
from sensor_msgs_py import point_cloud2

from ri_seaweed_interfaces.srv import GetObjects


class CameraObjectDetector(Node):
    def __init__(self):
        super().__init__('camera_object_detector')

        self.detect_objects_service = self.create_service(
            GetObjects,
            'get_objects',
            self.get_objects_callback
        )
        
        self.latest_cloud = None

        self.cloud_sub = self.create_subscription(
            PointCloud2,
            '/camera/camera/depth/color/points',
            self.cloud_callback,
            10
        )
    
    
    def cloud_callback(self, msg):
        self.latest_cloud = msg

    def detect_objects(self):
        # Program variables
        DB_epsilon = 0.01                                   # 0.05 works well
        DB_min_samples = 3                                  # 5 works well
        downsample = 10                                     # Only takes n-th point from the pointcloud (set to 1 for no downsampling)
        object_min_points = 4200                            # Objects from clusters with less points that this are removed (set to 0 to enable dynamic scaling)
        object_min_points_scale = 10                        # Dynamic scaling of min objects based on max depth from camera
        plane_distance_treshhold = 0.02                     # Threshold for points to count as a flat plane [m]
        min_bounds, max_bounds = [-1, -1, -1], [1, 1, 1]    # Bounds for x,y,z values for points for cropping [m]

        # Some rules to make the orientation deterministic, based on the current placement of the camera
        # and the reference frame of the end effector
        right_ref = np.array([1.0, 0.0, 0.0])  # cylinder x axis, longest axis, points to the camera right
        depth_ref = np.array([0.0, 0.0, 1.0])  # the z axis should point away from the camera
        # y axis is the cross product of x and z

        # Function generated by AI
        # Randomly samples 3 points, draws a plane between them and counts how many points fall on that plane
        # Repeats 'n_iter' times and returns the plane with the highest amount of points in it
        # Can only detect one plane at a time, and has a non-zero, though extremely small, chance of failing
        # to detect the correct plane
        def fit_plane_ransac(points, n_iter, distance_thresh):
            """
            Fit a plane ax + by + cz + d = 0 with simple RANSAC.
            Returns:
                inlier_mask: boolean mask of points belonging to the plane
            """
            if len(points) < 3:
                return np.zeros(len(points), dtype=bool)

            best_inliers = np.zeros(len(points), dtype=bool)
            best_count = 0

            rng = np.random.default_rng()

            for _ in range(n_iter):
                idx = rng.choice(len(points), size=3, replace=False)
                p1, p2, p3 = points[idx]

                v1 = p2 - p1
                v2 = p3 - p1
                normal = np.cross(v1, v2)
                norm = np.linalg.norm(normal)

                if norm < 1e-8:
                    continue

                normal = normal / norm
                d = -np.dot(normal, p1)

                distances = np.abs(points @ normal + d)
                inliers = distances < distance_thresh
                count = np.count_nonzero(inliers)

                if count > best_count:
                    best_count = count
                    best_inliers = inliers

            self.get_logger().info(f"Found plane with {best_count} points.")
            return best_inliers
        
        # Function for cropping the pointcloud to hardcoded bounds, in meters
        # Should be changed with cropping based on markers, such as fiducial markers, in the future
        def crop(points, min_bounds, max_bounds):
            mask = (
                (points[:, 0] >= min_bounds[0]) & (points[:, 0] <= max_bounds[1]) &
                (points[:, 1] >= min_bounds[0]) & (points[:, 1] <= max_bounds[1]) &
                (points[:, 2] >= min_bounds[0]) & (points[:, 2] <= max_bounds[1])
            )

            return points[mask]

        # Simple function for normalizing vector
        def normalize(v):
            n = np.linalg.norm(v)
            return v / n

        # Create a matrix of points in form:
        # [x1, y1, z1]
        # [x2, y2, z2]
        # [xn, yn, zn]
        cloud_array = point_cloud2.read_points_numpy(
            self.latest_cloud,
            field_names=("x", "y", "z"),
            skip_nans=True
        )

        points = np.asarray(cloud_array, dtype=np.float32).reshape(-1, 3)
        points = points[~np.all(points == 0, axis=1)]
        points = points[::downsample]
        points = crop(points, min_bounds, max_bounds)        

        # Removes planes using the RANSAC algorithm, to remove floors, walls, etc.,
        # until no more planes with enough points remain
        plane_point_thershold = 50000 / (downsample / 2)
        count = plane_point_thershold + 1

        while count > plane_point_thershold:
            plane_inliers = fit_plane_ransac(
                points,
                n_iter=200,
                distance_thresh=plane_distance_treshhold
            )

            count = np.count_nonzero(plane_inliers)

            if count > plane_point_thershold:
                points = points[~plane_inliers]
                self.get_logger().info(f"Removing plane with {count} points.")

        # Clustering the points with DBSCAN to find objects
        db = DBSCAN(eps=DB_epsilon, min_samples=DB_min_samples).fit(points)
        labels = db.labels_

        n_clusters_ = len(set(labels)) - (1 if -1 in labels else 0)
        n_noise_ = list(labels).count(-1)

        self.get_logger().info(f"Estimated number of objects {n_clusters_}")
        self.get_logger().info(f"Estimated number of noise points: {n_noise_}")

        # Removes the noise from the data set
        points = points[labels != -1]
        labels = labels[labels != -1]

        # Removes object with too few points
        unique_labels, points_per_object = np.unique(labels, return_counts=True)
        self.get_logger().info(f"Points per object cluster {np.sort(points_per_object)}")

        temp_points = np.array([])
        temp_labels = np.array([])

        if object_min_points == 0:
            object_min_points = (2000 / np.max(points[:, 2])) * object_min_points_scale / downsample
            self.get_logger().info(
                f"Dynamic minimal points per cluster to qualify as an object: {object_min_points}"
            )

        for i in range(len(points)):
            idx = np.where(unique_labels == labels[i])[0][0]
            
            if points_per_object[idx] > object_min_points:
                temp_points = np.append(temp_points, points[i])
                temp_labels = np.append(temp_labels, labels[i])

        labels = temp_labels
        points = np.reshape(temp_points, (-1, 3))

        # Find centers and directions of objects
        centroids = np.array([])
        longest_axises = np.array([])
        pca = PCA(n_components=1)

        for j in np.unique(labels):
            points_of_cluster = points[labels == j, :]

            # Longest axis for orientation
            pca.fit(points_of_cluster)
            longest_axises = np.append(longest_axises, pca.components_)

            # Old centroid method: mean of visible cluster points
            mean_centroid = np.mean(points_of_cluster, axis=0)

            # New centroid method: center of oriented bounding box in PCA space
            pca_full = PCA(n_components=3)
            pca_full.fit(points_of_cluster)

            R = pca_full.components_.T

            local_points = (points_of_cluster - mean_centroid) @ R

            local_min = np.min(local_points, axis=0)
            local_max = np.max(local_points, axis=0)

            local_bbox_center = 0.5 * (local_min + local_max)

            obb_centroid = mean_centroid + local_bbox_center @ R.T

            # Hybrid centroid:
            # X from the new oriented-bounding-box method
            # Y from the old mean-centroid method
            # Z from the new oriented-bounding-box method
            centroid = np.array([
                obb_centroid[0],
                mean_centroid[1],
                obb_centroid[2]
            ])

            centroids = np.append(centroids, centroid)

        # CENTERS AND DIRECTIONS
        centroids = np.reshape(centroids, (-1, 3))
        longest_axises = np.reshape(longest_axises, (-1, 3))

        coordinates = []
        orientations = []

        for c in range(len(centroids)):
            x_axis = normalize(longest_axises[c])  # x axis is made from the longest axis

            if np.dot(x_axis, right_ref) < 0:      # its direction is chosen to point right, PCA is random left/right
                x_axis = -x_axis

            z_axis = depth_ref - np.dot(depth_ref, x_axis) * x_axis
            z_axis = normalize(z_axis)

            y_axis = normalize(np.cross(z_axis, x_axis))
            z_axis = normalize(np.cross(x_axis, y_axis))  # Recompute Z for numerical orthogonality

            # Creates a rotation matrix for the axes and creates a quaternion from it
            rot_matrix = np.column_stack((x_axis, y_axis, z_axis))

            # Rotates the camera data to match the camera referance frame
            camera_offset = np.array([
                [-1.0,        0.0,       0.0],
                [ 0.0,        1.0,       0.0],
                [ 0.0,        0.0,      -1.0]
            ])

            qx, qy, qz, qw = Rotation.from_matrix(rot_matrix @ camera_offset).as_quat()

            coordinates.append(centroids[c])
            orientations.append([qx, qy, qz, qw])

        return np.array(coordinates), np.array(orientations)
    
    def get_objects_callback(self, request, response):
        coordinates, orientations = self.detect_objects()

        response.success = True
        response.message = "TEST"

        response.object_pose.header.stamp = self.get_clock().now().to_msg()
        response.object_pose.header.frame_id = "camera_frame"

        response.object_pose.pose.position.x = float(coordinates[0, 0])
        response.object_pose.pose.position.y = float(coordinates[0, 1])
        response.object_pose.pose.position.z = float(coordinates[0, 2])

        response.object_pose.pose.orientation.x = float(orientations[0, 0])
        response.object_pose.pose.orientation.y = float(orientations[0, 1])
        response.object_pose.pose.orientation.z = float(orientations[0, 2])
        response.object_pose.pose.orientation.w = float(orientations[0, 3])

        self.get_logger().info(f"{response}")

        return response


def main():
    rclpy.init()
    get_objects_service = CameraObjectDetector()
    rclpy.spin(get_objects_service)
    rclpy.shutdown()


if __name__ == '__main__':
    main()